.PHONY: all clean

PROJECT_NAME = proxima
PROJECT_FULL_NAME = mechanika-design/proxima

CC = x86_64-w64-mingw32-gcc
AR = x86_64-w64-mingw32-ar
CFLAGS = -D_DEFAULT_SOURCE -g -I${INCLUDE_PATH} -O2 -std=gnu99

all:
	@${MAKE} CC=${CC} AR=${AR} CFLAGS="${CFLAGS}"

clean:
	@${MAKE} $@