.PHONY: all clean

INCLUDE_PATH = include
LIBRARY_PATH = lib
SOURCE_PATH = src

CC = emcc
AR = emar
CFLAGS = -D_DEFAULT_SOURCE -g -I${INCLUDE_PATH} -O2 -std=gnu99

# CFLAGS += -Wall -Wpedantic -Wno-unused-but-set-variable \
		-Wno-unused-command-line-argument -Wno-unused-value -Wno-unused-variable

all:
	@${MAKE} CC=${CC} AR=${AR} CFLAGS="${CFLAGS}"

clean:
	@${MAKE} $@